
[functions.fetchStrava]
enabled = true
verify_jwt = true
import_map = "./functions/fetchStrava/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetchStrava/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetchStrava/*.html" ]

[functions.strava-callback]
enabled = true
verify_jwt = false
entrypoint = "./functions/strava-callback/index.ts"
